#!/bin/sh
mkdir -p /home/dotcloud/data/media /home/dotcloud/data/static
cp -r /home/dotcloud/code/yichengwenhua/static /home/dotcloud/data
python yichengwenhua/manage.py syncdb --all --noinput
python yichengwenhua/manage.py migrate --fake
python mkadmin.py
python yichengwenhua/manage.py collectstatic --noinput
